### ISSUE TITLE
Terminal Client 

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion#135]
Backend ohne Frontend steuern: Debuggen, reloaden, konfigurieren, Testdaten senden, in bus "reinhacken"

Lina, Jan

**Comment by fussel178** [comment]
https://github.com/vert-x3/vertx-eventbus-bridge-clients/tree/master/java

**Comment by fussel178** [comment]
Superseded by https://github.com/wuespace/telestion-terminal-client/issues/77
