### ISSUE TITLE
ROS Connector

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion#137]
We need to integrate ROS for T-REX. Here are some links:

https://wiki.ros.org/rosjava/Tutorials/kinetic/No%20Ros%20Installation
https://wiki.ros.org/rosjava
http://wiki.ros.org/android

A "good" API documentation:
http://rosjava.github.io/rosjava_core/hydro/index.html

**Comment by fussel178** [comment]
Moving to YouTrack.

For further information:
https://telestion.youtrack.cloud/issue/TELESTION-438/ROS-Integration
