### ISSUE TITLE
Convert the main repo to a starting point.

### ISSUE THREAD

**Issue by jvpichowski** [wuespace/telestion#98]
The telestion repo should work as a starting point. Therefore it needs descriptions of the other repositories and projects to be a guiding help. This could happen through markdown files. I would propose to use the docs dita repo to build up the documentation and automatically generate a target set and pull request with the appreciated information. This could happen with: https://www.dita-ot.org/dev/topics/dita2markdown.html

**Comment by fussel178** [comment]
Due to v2 release of our new documentation website, I think we should convert this repository to a Telestion issue tracker.
Issues that don't fit into a specific repository very well or work in a greater context should be moved here.
